local names = {
	 'gentle_about', 'gentle_accept database', 'gentle_add_column', 'gentle_add_database', 'gentle_add_image', 'gentle_add_row', 'gentle_address book';
	 'gentle_advance', 'gentle_advertising', 'gentle_alarm_clock', 'gentle_sorting_az','gentle_sorting_za','gentle_answers','gentle_approval','gentle_approve','gentle_chart_area';
	 'gentle_assistant', 'gentle_file_audio', 'gentle_automatic', 'gentle_automovitve', 'gentle_decision_bad', 'gentle_chart_bar', 'gentle_bearish', 'gentle_binoculars';
	 'gentle_biohazard', 'gentle_biomass', 'gentle_biotech', 'gentle_bookmark', 'gentle_briefcase', 'gentle_broken link', 'gentle_bullish', 'gentle_business', 'gentle_business contact';
	 'gentle_businessman', 'gentle_businesswoman', 'gentle_butting in', 'gentle_cable release', 'gentle_calculator', 'gentle_calendar', 'gentle_call transfer', 'gentle_callback', 'gentle_camcorder', 'gentle_camcorder pro';
	 'gentle_camera_camera','gentle_camera_addon','gentle_camera_identification','gentle_cancel','gentle_candle sticks','gentle_capacitor','gentle_cell phone','gentle_battery_charge','gentle_checkmark','gentle_circuit','gentle_clapperboard';
	 'gentle_clear flters','gentle_clock','gentle_rose', 'gentle_cloth','gentle_collaboration','gentle_arrow_collapse', 'gentle_collect', 'gentle_chart_combo','gentle_comments', 'gentle_camera_compact', 'gentle_conference call', 'gentle_contacts', 'gentle_copyleft','gentle_copyright';
	 'gentle_crystal oscillator','gentle_currency rxchange','gentle_cursor','gentle_customer support','gentle_dam','gentle_data_backup','gentle_data_configuration','gentle_data_encryption','gentle_data_protection','gentle_data_recovery','gentle_data_sheet';
	 'gentle_database','gentle_debt', 'gentle_decision_decision','gentle_delete_column','gentle_delete_database','gentle_delete_row','gentle_department','gentle_deployment','gentle_diploma_1','gentle_diploma_2','gentle_disapprove','gentle_disclaimer','gentle_dislike','gentle_display';
	 'gentle_do not_inhale','gentle_do not_insert','gentle_do not_mix','gentle_document','gentle_donate','gentle_chart_doughnut','gentle_arrow_down','gentle_arrow_down left','gentle_arrow_down right','gentle_download','gentle_edit image','gentle_electrical_sensor';
	 'gentle_electrical_threshold','gentle_electricity','gentle_electro devices','gentle_electronics','gentle_battery_empty', 'gentle_trash_empty','gentle_end call','gentle_engineering','gentle_entering heaven','gentle_arrow_expand','gentle_expired';
	 'gentle_export','gentle_external','gentle_factory','gentle_factory breakdown','gentle_faq','gentle_feed in','gentle_feedback','gentle_file_file','gentle_filing cabinet';
	 'gentle_filled filter', 'gentle_film_film','gentle_film_reel','gentle_filter','gentle_fine print','gentle_flash_auto','gentle_flash_off','gentle_flash_on','gentle_chart_flow','gentle_folder','gentle_frame';
	 'gentle_battery_full', 'gentle_trash_full','gentle_gallery', 'gentle_genealogy','gentle_sorting_longest','gentle_sorting_shortest','gentle_globe','gentle_decision_good','gentle_graduation cap';
	 'gentle_grid','gentle_headset','gentle_heat map','gentle_battery_high','gentle_high priority','gentle_home','gentle_icons8','gentle_idea','gentle_file_image','gentle_import','gentle_in transit','gentle_info';
	 'gentle_inspection','gentle_integrated webcam','gentle_internal','gentle_invite','gentle_ipad','gentle_iphone','gentle_key','gentle_kindle','gentle_landscape','gentle_leave','gentle_arrow_left','gentle_arrow_left down','gentle_arrow_left down curve','gentle_arrow_left up','gentle_arrow_left up curve';
	 'gentle_library','gentle_light at the end of tunnel','gentle_like_like','gentle_like_placeholder','gentle_chart_line','gentle_link','gentle_list','gentle_lock','gentle_landscape','gentle_portrait','gentle_battery_low','gentle_priority_low','gentle_decision_make','gentle_manager';
	 'gentle_priority_medium','gentle_menu','gentle_battery_middle','gentle_mind map','gentle_minus','gentle_missed call','gentle_mms','gentle_money transfer','gentle_multiple_cameras','gentle_multiple_devices','gentle_multiple_inputs','gentle_multiple_smartphones','gentle_music';
	 'gentle_negative dynamic','gentle_decision_neutral','gentle_neutral trading','gentle_news','gentle_arrow_next','gentle_night_landscape','gentle_night_portrait','gentle_no idea','gentle_no video','gentle_nook','gentle_sorting_123','gentle_sorting_321','gentle_ok','gentle_camera_old','gentle_online support','gentle_opened folder';
	 'gentle_org unit','gentle_organization','gentle_overtime','gentle_package','gentle_paid','gentle_panorama','gentle_parallel tasks','gentle_phone','gentle_android','gentle_photo reel','gentle_picture','gentle_chart_pie','gentle_planner','gentle_plus','gentle_podium_audience','gentle_podium_speaker','gentle_podium_no speaker','gentle_portrait mode','gentle_positive dynamic','gentle_arrow_previous';
	 'gentle_print','gentle_privacy','gentle_process','gentle_puzzel','gentle_questions','gentle_radar plot','gentle_rating','gentle_ratings','gentle_reading','gentle_reading ebook','gentle_redo','gentle_refresh','gentle_registered trademark','gentle_remove image','gentle_reuse','gentle_arrow_right','gentle_arrow_right down','gentle_arrow_right down curve','gentle_arrow_right up','gentle_arrow_right up curve';
	 'gentle_camera_rotate','gentle_to landscape','gentle_to portrait','gentle_ruler','gentle_rules','gentle_safe','gentle_sales performance','gentle_scatter plot','gentle_search','gentle_kiosk','gentle_slefie','gentle_serial tasks','gentle_service mark','gentle_services','gentle_settings','gentle_share','gentle_shipped','gentle_shop','gentle_signature';
	 'gentle_sim_card','gentle_sim_Card chip','gentle_slr back','gentle_tablet','gentle_sms','gentle_sound recording copyright','gentle_speaker','gentle_sports mode','gentle_multiple_photos','gentle_start','gentle_statistics','gentle_support','gentle_survey','gentle_camera_switch','gentle_synchornize','gentle_tablet andriod','gentle_template';
	 'gentle_timeline','gentle_todo lst','gentle_smartphone','gentle_trademark','gentle_tree structure','gentle_two smartphones','gentle_undo','gentle_unlock','gentle_arrow_up','gentle_arrow_up left','gentle_arrow_up right','gentle_upload','gentle_video call','gentle_file_video','gentle_video projector','gentle_view details','gentle_vip','gentle_voice presentation','gentle_voicemail','gentle_webcam','gentle_workflow'
}

Spice.Iconography.insertIconList('rbxassetid://1784678984',21, 15, 48, 48, names)