Spice.Properties.new("TableLayout",function(who, ...)
	Spice.Instance.newInstance('UITableLayout',who,...)
end)
Spice.Properties.new("TextConstraint",function(who, ...)
	Spice.Instance.newInstance('UITextConstraint',who,...)
end)
Spice.Properties.new("SizeConstraint",function(who, ...)
	Spice.Instance.newInstance('UISizeConstraint',who,...)
end)
Spice.Properties.new("AspectRatio",function(who, ...)
	Spice.Instance.newInstance('UIAspectRatioConstraint',who,...)
end)
Spice.Properties.new("List",function(who, ...)
	Spice.Instance.newInstance('UIListLayout',who,...)
end)
Spice.Properties.new("Grid",function(who, ...)
	Spice.Instance.newInstance('UIGridLayout',who,...)
end)
Spice.Properties.new("Page",function(who, ...)
	Spice.Instance.newInstance('UIPageLayout',who,...)
end)
Spice.Properties.new("Spacing",function(who, ...)
	Spice.Instance.newInstance('UIPadding',who,...)
end)
Spice.Properties.new("Draggable",function(who, ...)
	who.Active = true
	who.Draggable = true
end)
