Spice.Properties.new("TableLayout",function(who, props)
	Spice.Instance.newInstance('UITableLayout',who, props and type(props) == 'table' and props or nil)
end)
Spice.Properties.new("TextConstraint",function(who, props)
	Spice.Instance.newInstance('UITextConstraint',who, props and type(props) == 'table' and props or nil)
end)
Spice.Properties.new("SizeConstraint",function(who, props)
	Spice.Instance.newInstance('UISizeConstraint',who, props and type(props) == 'table' and props or nil)
end)
Spice.Properties.new("AspectRatio",function(who, props)
	Spice.Instance.newInstance('UIAspectRatioConstraint',who, props and type(props) == 'table' and props or nil)
end)
Spice.Properties.new("List",function(who, props)
	Spice.Instance.newInstance('UIListLayout',who, props and type(props) == 'table' and props or nil)
end)
Spice.Properties.new("Grid",function(who, props)
	Spice.Instance.newInstance('UIGridLayout',who, props and type(props) == 'table' and props or nil)
end)
Spice.Properties.new("Page",function(who, props)
	Spice.Instance.newInstance('UIPageLayout',who, props and type(props) == 'table' and props or nil)
end)
Spice.Properties.new("Spacing",function(who, props)
	Spice.Instance.newInstance('UIPadding',who, props and type(props) == 'table' and props or nil)
end)
